parameters:
    sylius.form.type.order.validation_groups: [mbiz_coliship]
    sylius.form.type.address.validation_groups: [mbiz_coliship]
    sylius.form.type.checkout_address.validation_groups: [mbiz_coliship]

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false
        Sylius\Component\Resource\Model\ResourceInterface:
            autowire: false
            
    MonsieurBiz\SyliusColishipPlugin\:
        resource: '../../'

    MonsieurBiz\SyliusColishipPlugin\Directory\DirectoryInterface $fmtDirectory: '@MonsieurBiz\SyliusColishipPlugin\Directory\FmtDirectory'
    MonsieurBiz\SyliusColishipPlugin\Directory\DirectoryInterface $orderPaymentStateDirectory: '@MonsieurBiz\SyliusColishipPlugin\Directory\OrderPaymentStateDirectory'
    MonsieurBiz\SyliusColishipPlugin\Directory\DirectoryInterface $orderShippingStateDirectory: '@MonsieurBiz\SyliusColishipPlugin\Directory\OrderShippingStateDirectory'
    MonsieurBiz\SyliusColishipPlugin\Directory\DirectoryInterface $shippingMethodCodeDirectory: '@MonsieurBiz\SyliusColishipPlugin\Directory\ShippingMethodCodeDirectory'
    MonsieurBiz\SyliusColishipPlugin\Mapping\MappingInterface $fmtMapping: '@MonsieurBiz\SyliusColishipPlugin\Mapping\FmtMapping'
    MonsieurBiz\SyliusColishipPlugin\Exporter\ExporterInterface $colishipExporter: '@MonsieurBiz\SyliusColishipPlugin\Exporter\ColishipExporter'
